### ISSUE TITLE
Colab Notebook AttributeError again?

### ISSUE THREAD

**Issue by WorldofDepth** [compphoto/BoostingMonocularDepth#21] opened 2021-07-30 19:41 UTC
Hi, it seems like this error is occuring often when I try to use the Colab Notebook lately. If I reset the runtime and start over, sometimes it works, and sometimes not. It happens with both MiDaS and LeReS, and I don't think it depends on what file(s) or filetypes are in the inputs folder. However, it does appear to work after this error if I create a new folder for the input images, move the images into that folder, and update the directory in the last code cell to match. But how can this be avoided? Please advise—thank you! 

I see this error was mentioned before and a bug was fixed—maybe it's the same issue again? A user also mentioned a .ipynb_checkpoint file in the inputs file, but when I try to run a command to remove it, it's not found. But the fact that using a different folder works suggest maybe it's a related problem?

`Traceback (most recent call last):
  File "run.py", line 580, in <module>
    run(dataset_, option_)
  File "run.py", line 107, in run
    for image_ind, images in enumerate(dataset):
  File "/content/BoostingMonocularDepth/utils.py", line 215, in __getitem__
    return Images(self.rgb_image_dir, self.files, index)
  File "/content/BoostingMonocularDepth/utils.py", line 148, in __init__
    self.rgb_image = read_image(os.path.join(self.root_dir, name))
  File "/content/BoostingMonocularDepth/utils.py", line 27, in read_image
    if img.ndim == 2:
AttributeError: 'NoneType' object has no attribute 'ndim'`

**Comment by miangoleh** [comment] 2021-07-30 19:55
This seems to happen in case the input directory is empty or there is an unsupported file inside it. Make sure to put the images in the correct location and that there is not extra file present in the input folder.

**Comment by WorldofDepth** [comment] 2021-07-30 20:00
Thank you…I have been using JPG files, and always check the folder contents. Unless there is a hidden file generated by the code or the upload process, I don't see anything else. I don't know if there's an option to display .hidden files in Colab.

**Comment by miangoleh** [comment] 2021-07-30 20:04
I will try to handle it within code implementation of reading image files to make sure the existence of non-image files inside the input folder will not result in an error. 

Thanks

**Comment by WorldofDepth** [comment] 2021-07-30 20:09
OK, thank you!

By the way, I *have* found a hidden file—actually a hidden folder? When I upload a test file to the inputs folder and run the command `!ls /content/inputs -al`, it shows, for example:

```
total 640
drwxr-xr-x 3 root root   4096 Jul 30 20:02 .
drwxr-xr-x 1 root root   4096 Jul 30 20:01 ..
drwxr-xr-x 2 root root   4096 Jul 30 20:02 .ipynb_checkpoints
-rw-r--r-- 1 root root 641643 Jul 30 20:02 t6.jpg
```

Before uploading, the same command shows the folder empty.

If I run `!rmdir /content/inputs/.ipynb_checkpoints` to remove this hidden folder, then the programs run without error.

**Comment by patatattak** [comment] 2021-09-04 03:18
Hello,

I get the same error, always on the second file i upload on Colab. It's definitely a problem with hidden files.

The following change seems to correct it : 


In utils.py, line 209 (function __init__ of ImageDataSet class), replace this line : 
self.files = sorted(os.listdir(self.rgb_image_dir))
by this line : 
self.files = sorted([f for f in os.listdir(self.rgb_image_dir) if f.endswith('.png')])

(or .jpg if you use jpeg files)

**Comment by SlimeVRX** [comment] 2023-08-02 07:06
> Hello,
> 
> I get the same error, always on the second file i upload on Colab. It's definitely a problem with hidden files.
> 
> The following change seems to correct it :
> 
> In utils.py, line 209 (function **init** of ImageDataSet class), replace this line : self.files = sorted(os.listdir(self.rgb_image_dir)) by this line : self.files = sorted([f for f in os.listdir(self.rgb_image_dir) if f.endswith('.png')])
> 
> (or .jpg if you use jpeg files)

Thank! This helped me to solve the problem in Colab

**Comment by miangoleh** [comment] 2024-03-05 18:36
The issue is fixed by filtering file formats in the dataloader. Only png, jpg, and jpeg images are loaded.

**Closed by miangoleh** 2024-03-05 18:36 UTC
